language: objective-c
podfile: Example/Podfile
osx_image: xcode9.2
script:
- set -o pipefail && xcodebuild test -workspace Example/BATabBarController.xcworkspace -scheme BATabBarController-Example -sdk iphonesimulator -destination 'name=iPhone 6 Plus' ONLY_ACTIVE_ARCH=NO | xcpretty
